MANIFEST.in
https://pypi.python.org/pypi/check-manifest/0.23
Easy to check your manifest
=> Fix manifest to include correct files

oscarapi/basket/operations.py, oscarapi/serializers/checkout.py
=> Use OrderTotalCalculator to calculate order total

oscarapi/middleware.py
=> Added a basketmiddleware that solves the problem of mixing regular oscar

setup.py
probably from bad merge conflict
=> remove duplicity from insall requires

oscarapi/middleware.py
=> Fixes #43 Reference local requst variable rather than instance variable

oscarapi/middleware.py
=> Fixes #41 Fixes usage of super() in ApiBasketMiddleware

.travis.yml, Makefile
=> Minor maintenance

oscarapi/serializers/checkout.py, oscarapi/tests/testcheckout.py, oscarapi/views/checkout.py, setup.py
Add guest_email field to checkout view. This is needed for anonymous checkouts.
=> Add guest_email to checkout view

.travis.yml, oscarapi/tests/testcheckout.py, oscarapi/tests/testlogin.py, oscarapi/tests/utils.py, oscarapi/utils.py
NOT READY FOR MERGE YET - wait for travis tests.
=> Add python 3 support and testing

oscarapi/serializers/basket.py, oscarapi/serializers/checkout.py, oscarapi/serializers/fields.py, oscarapi/serializers/login.py, oscarapi/serializers/product.py, oscarapi/views/basic.py, oscarapi/views/basket.py, oscarapi/views/checkout.py
Mostly to make sure we have a consistent code-layout and make sure we do what restframework 3 wants us to do.
=> Views and serialisers cleanup

.travis.yml, docs/source/usage/communicate_with_the_api.rst, oscarapi/serializers/basket.py, oscarapi/tests/testbasket.py, oscarapi/views/basket.py
* Added documentation (and fixed an issue with LineAttributes) for modifying basketlines.
* Enforce that the AddProductSerializer can only be used to add products to the basket
=> Fixes for basket lines

docs/source/usage/outofthebox.rst
If you don't put rest framework in installed apps you'll have template problems.
=> Fix rest_framwork template problems.

.travis.yml, README.rst, docs/source/index.rst, oscarapi/tests/testlogin.py, sandbox/settings.py, sandbox/urls.py, setup.py
- Allow a billing address
- Fixed compatibility issues for django 1.10 / oscar 1.4
- Updated test matrix
- Test with python 3.6
=> Prepare for release 1.0.11

oscarapi/tests/testproduct.py, oscarapi/views/basic.py
=> Fetch products properly in ProductPrice and ProductAvailability views

docs/source/index.rst
=> fix typo in index.rst

MANIFEST.in
=> Don't include the sandbox and other unwanted things in the dist

.travis.yml
See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
=> container based infra is deprecated by travis

oscarapi/basket/operations.py, oscarapi/tests/unit/testbasket.py
Adds explicit tests for basket merge strategy
=> fixes #165

oscarapi/urls.py
- Removed url in favour of path and re_path.
- CountryDetail's url regex only accepts two caracters for resolving
=> Replace url with path and re_path.

oscarapi/serializers/fields.py, oscarapi/serializers/product.py, oscarapi/tests/unit/testdata/child-product.json, oscarapi/tests/unit/testproduct.py, oscarapi/utils/exists.py
Child products have a lot of empty values.
Added validation and errors to allow for child products
=> Child products

oscarapi/serializers/fields.py, oscarapi/tests/unit/testproduct.py
This lets people see which attribute it is that the validation errors apply to
=> Have more informative validation errors on attributes.

oscarapi/views/admin/order.py, oscarapi/views/basket.py, oscarapi/views/checkout.py
Fixes couple of broken apis reported in fixes #189
=> Fixes a couple of broken apis

oscarapi/serializers/checkout.py, oscarapi/tests/unit/testcheckout.py
Use a different field for the calculated order total. See also https://github.com/django-oscar/django-oscar-api/issues/188
=> Do not change the "total" field type from Decimal to Price

Makefile, oscarapi/serializers/fields.py, oscarapi/tests/utils.py, setup.cfg, setup.py
Added:
- flake8 config which is 100% black compatible
- flake8 bugbear plugin
=> Basic linting with flake8

oscarapi/serializers/fields.py, oscarapi/tests/unit/testproduct.py, oscarapi/utils/files.py, oscarapi/views/basket.py
=> Download hash internal

oscarapi/views/product.py
Make default state readable dynamically by DRF ([https://www.django-rest-framework.org/api-guide/schemas/#generating-a-dynamic-schema-with-schemaview](url))
=> Fix DRF openapi integration

oscarapi/middleware.py, oscarapi/tests/unit/testmiddleware.py
=> Fix APIGatewayMiddleware handling of valid API keys.

oscarapi/views/basket.py
Related to https://github.com/django-oscar/django-oscar-api/issues/227
=> BasketLineDetail: Use DRF get_object_or_404

oscarapi/serializers/admin/product.py, oscarapi/tests/unit/testproduct.py
=> Fix category slug always required

docs/source/usage/communicate_with_the_api.rst, docs/source/usage/settings.rst, oscarapi/serializers/login.py, oscarapi/tests/unit/testlogin.py, oscarapi/urls.py, oscarapi/views/login.py, oscarapi/views/root.py, sandbox/settings/sandbox.py
=> Add user registration endpoint

docs/source/index.rst
Corrected E-Cmmerce to E-Commerce in the documentation
=> fix-typo-e-commerce

oscarapi/serializers/utils.py, oscarapi/tests/unit/testserializers.py
=> Do not monkeypatch DRF ImageField implicitly like this

oscarapi/serializers/checkout.py, oscarapi/tests/unit/testvoucher.py
Voucher discount appeared twice in the order response. With this PR, it is excluded from offer discounts.
=> [Fix] Remove voucher discount in offer discount

docs/source/topics/the_admin_api.rst
Tried with django-oscar-api 3.2.4, I don't know if it changed recently or not.
=> FIX documentation: it's not a post, it's a patch to upload a product image

oscarapi/serializers/fields.py, oscarapi/serializers/product.py, oscarapi/utils/attributes.py
This PR restores that functionality.
=> The image and file fields where nolonger working.
