oscarapi/basket/operations.py
Applicator.apply parameters have changed in Oscar 1.1. Update the call accordingly.
=> Update Applicator.apply call for Oscar1.1

oscarapi/serializers/basket.py, oscarapi/serializers/checkout.py, oscarapi/serializers/fields.py
When using the US strategy, tax isn't know until the shipping address is
entered. This causes BasketSerializer to throw an exception because access the
total_incl_tax, total_incl_tax_excl_discounts, or total_tax properties throw
TaxNotKnown when is_tax_known is false. This fixes the issue by detecting that
case and acknowledging in the API that tax isn't yet known.
=> Fix basket serializer when tax is not known

oscarapi/utils.py
In Python 3, the method used to extend the field mappings dictionary threw an
exception because keyword arguments must be strings. This commit fixes that
exception.
=> Fix Keyword Arguments error in Python 3.5

oscarapi/middleware.py
When a response is a redirect, the request.user attribute is never set. This
check prevents through an exception when that is the case.
=> Fix missing attribute request.user on redirect responses

Dockerfile, docker-compose.yml
Just for developer convenience, it's nice to have this set up. Makes messing with other versions of Python or misc libraries easier and prevents having to deal with a virtualenv.
=> Add Docker configuration for testing convenience 

oscarapi/serializers/checkout.py, oscarapi/tests/testcheckout.py
This results in the user getting a 406 Not Acceptable, rather than a 500
Server Error, resulting from an exception thrown by Oscar.
=> Throw a ValidationError if a user tries to checkout with an empty basket

README.rst, docs/source/index.rst, docs/source/usage/customizing_oscarapi.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs link for their .org -> .io migration for hosted projects

oscarapi/middleware.py
This tries to fix #34. The problem is that adding the basket cookie to request tricks the super call in thinking that the cookie is already there. This is because of has_basket_cookie in the [super call](https://github.com/django-oscar/django-oscar/blob/913da107f1f760a707a0555d06663fc5dbcea4b2/src/oscar/apps/basket/middleware.py):
```
def process_response(self, request, response):
...
has_basket_cookie = (
cookie_key in request.COOKIES
and cookie_key not in cookies_to_delete)
if (request.basket.id and not request.user.is_authenticated()
and not has_basket_cookie):
...
```
I haven't found a better way than just rewrite and streamline part of the super call in ApiBasketMiddleware.process_response and skip the super call altogheter. I know this is not optimal but I couldn't find a better …
=> Change process_response to have API-created basket cookie added to response

oscarapi/views/login.py
The login serializer looks as if it is configurable, but in fact the configured serializer class is never used.
=> Use configured serializer in stead of the hardcoded one

oscarapi/views/basket.py
There is a case when request.basket is empty, but get_basket(request) will return a basket with products based on the cookies
=> basket/shipping-methods could use another basket than /basket

oscarapi/tests/testcheckout.py, oscarapi/views/checkout.py, oscarapi/views/utils.py
See also the discussion here: https://github.com/django-oscar/django-oscar-api/pull/99
Django REST framework has some permission checking in the `BrowsableAPI`. Unfortunately this is not the cleanest code, see this issue: https://github.com/encode/django-rest-framework/issues/2089
This code is there for a long time (hence: is included in a lot of REST framework versions).
So, it will check the permissions of the objects here: https://github.com/encode/django-rest-framework/blob/master/rest_framework/renderers.py#L444 and here: https://github.com/encode/django-rest-framework/blob/master/rest_framework/renderers.py#L431
Note that it will do this for all views which have 1 or more serializers, not checking or depending on the type to determine if it should show a form or not:
```python
if …
```
=> The checkout view should not use the wrong mixin to check the basket ownership

oscarapi/views/login.py
For some reason the merged basket was deleted but oscar already has a status for that - MERGED. It makes super difficult to debug complex cases if anonymous basket got deleted.
=> No need to delete the merged anonymous basket after merge

.travis.yml, docs/source/changelog.rst, docs/source/index.rst, oscarapi/fixtures/attributeoption.xml, oscarapi/fixtures/product.xml, oscarapi/fixtures/productattribute.xml, oscarapi/fixtures/productattributevalue.xml, oscarapi/fixtures/productclass.xml, oscarapi/serializers/product.py, oscarapi/tests/testproduct.py, setup.py
These changes came from these commits:
- datetime: https://github.com/django-oscar/django-oscar/commit/b3875209d7ab8584b2e8e779b1f0ac0062dea940
- multioption: https://github.com/django-oscar/django-oscar/commit/246c38e8ecde95f2f22f7faa7696568effc0f790
=> oscarapi now correctly keeps the types of product attributes as defined in the ProductType.

oscarapi/views/basic.py
Without this change, this call will return:
TypeError: object of type 'map' has no len()
On python 3.
=> Fix for Python 3 compatibility

oscarapi/middleware.py, oscarapi/tests/test_middleware.py
`authentication.get_authorization_header` returns bytestring and in Python3 `'foo'` and `b'foo'` are not same.
For that reason `models.ApiKey.objects.filter(key=key).exists()` returns False.
=> Fix ApiGatewayMiddleWare in Python3

oscarapi/serializers/checkout.py, oscarapi/serializers/login.py
The main change here is changing the type of default fields for `OrderLineSerializer` from `list` to `tuple`. This is not critical, but sometimes in projects, I need to override some serializers and add additional fields.
E.g.
```python
class UpdatedOrderSerializer(OrderSerializer):
additional_field = ...
class Meta(OrderSerializer.Meta):
fields = OrderSerializer.Meta.fields + ('additional_field',)
```
Only for `OrderLineSerializer` I need to use `list`.
```python
fields = OrderLineSerializer.Meta.fields + ['additional_field']
```
And this looks a bit inconsistent.
=> Improve consistency in serializers

oscarapi/tests/unit/testcheckout.py, oscarapi/tests/utils.py
There were 3 skipped tests:
1. `test_checkout_header`
2. `test_cart_immutable_after_checkout`
3. `test_client_can_not_falsify_picing`
3rd test `test_client_can_not_falsify_picing` renamed to `test_client_cannot_falsify_shipping_charge` (since we already have test for total price `test_checkout_total_error`). Because of this `test_checkout_total_error` renamed to `test_client_cannot_falsify_total_price`.
All other tests here were refactored to improve readability.
Refs: #171
=> Add skipped and refactor existing checkout tests

oscarapi/serializers/product.py
`Meta` class is needed for subclasses of `ModelSerializer`.
=> Remove `Meta` class from `AddProductSerializer`

oscarapi/views/admin/product.py
Since construct_id_filter can build a uniquely identifying query from the
posted data, we can have update on the list view. This comes invery handy if
you are synchronizing data and have idea what the id of the objects is.
=> PUT and PATCH without specifying ID

oscarapi/tests/unit/testbasket.py, oscarapi/views/basket.py
The current implementation doesn't account for previously added lines of the same product.
=> Fix quantity validation in AddProductView

oscarapi/tests/unit/testproduct.py, oscarapi/views/admin/product.py
This is a very annoying bug. If you are not sending enough info to the api to be able to infer which object is meant, a MultipleObjectsReturned error occurs. This fixes that so it will show a proper error message.
=>  Added error message when construct_id_filter does not construct a useful filter.

docs/source/usage/the_admin_api.rst, oscarapi/serializers/fields.py, oscarapi/tests/unit/testproduct.py, oscarapi/utils/files.py
Also try to parsed a sha1 hash from the url, and store it as an
attribute, so the file_hash function will use it. You can use this feature
to avoid unnescessary downloading of files. Just compute the hash on the
client side and send it along in the url like this::
http://example.com/image.jpg?sha1=751499a82438277cb3cfb5db268bd41696739b3b
It will only download if not allready available locally.
=> Defer downloading of images until the file data is accessed.

oscarapi/views/basket.py, oscarapi/views/checkout.py, oscarapi/views/login.py, oscarapi/views/product.py, oscarapi/views/root.py
When you want to use [URLPathVersioning](https://www.django-rest-framework.org/api-guide/versioning/#urlpathversioning), all API views will receive an extra `version` keyword parameter.
The default API Views of REST Framework do accept this with `**kwargs` so I added this to the views in OscarAPI as well. The tests all pass, so there is not a backward compatibility issue.
I'll update the release notes mentioning that users should modify their oscarapi overrides to accept the `*args` and `**kwargs` arguments.
=> Accept *args and **kwargs so DRF versioning will work as expected

oscarapi/tests/unit/testadminapi.py, oscarapi/urls.py
So it's easier to customize when you would like to change / adapt the mountpoint, add url's to it, mount it with a different name etc.
=> Mount the admin api on the /admin endpoint with path()

oscarapi/serializers/checkout.py
OrderPlacementMixin does:
```
if 'request' not in kwargs:
request = getattr(self, 'request', None)
else:
request = kwargs.pop('request')
```
And uses the request in determining which site the order was placed on. WIthout this change oscarapi con not work in a multisite context.
=> Make sure the OrderPlacementMixin can find the request.

oscarapi/serializers/checkout.py, oscarapi/tests/unit/testcheckout.py
When no user is attached to the order the email property will be the order.guest_email.
When a user is attached to the order the email property will be the order.user.email
A this moment there is no way of getting the order email via the api because the user serializer doesn't have a email field
for some reason the communication app was not in the sandbox installed apps. I couldn't migrate and test without this.
=> Replace guest email with email property on order API

docs/source/usage/settings.rst, oscarapi/serializers/admin/user.py, oscarapi/serializers/login.py, oscarapi/tests/unit/testbasket.py, oscarapi/tests/unit/testlogin.py, oscarapi/tests/unit/testuser.py, oscarapi/urls.py, oscarapi/views/admin/user.py, oscarapi/views/login.py, sandbox/settings/sandbox.py
Use a separate user view (and serializer) for regular users and Admin API users. Allow user details to be visible, which can be controlled with a setting. See also #241 
Todo:
=> Split user detail views for end-users and the Admin API

oscarapi/serializers/product.py
Renamed ChildProductserializer to ChildProductSerializer to follow rest of the naming convention, fixes #281
=> Renamed ChildProductserializer to ChildProductSerializer

oscarapi/middleware.py, oscarapi/views/login.py
Only flush the session when logging out, so only the data from the session is deleted and not the whole session. This way the `SessionMiddleware` is still able to delete the associated session cookie. 
When the session is completely deleted the `try..except AttributeError` clause will return the response immediately without deleting the cookie, see below.
Taken from [django/contrib/sessions/middleware.py](https://github.com/django/django/blob/cfe3008123ed7c9e3f3a4d51d4a22f9d96634e33/django/contrib/sessions/middleware.py#L22-L42):
```python
def process_response(self, request, response):
"""
If request.session was modified, or if the configuration is to save the
session every time, save the changes and set a session cookie or delete
the session cookie if the session has been emptied.
""" …
```
=> Do not completely delete the session when logging out

oscarapi/tests/unit/test_get_api_class.py, oscarapi/utils/loading.py
When get_api_class or get_api_classes is imported in a file that is parsed during the django settings configuration, OSCARAPI_OVERRIDE_MODULES could be pinned to the wrong value.
get_api_class now reads the value from settings when it is called instead of statically defining it in the module. It is now safe to::
from oscarapi.utils.loading import get_api_class, get_api_classes
In files that are parsed diring django setting configuration, avoiding ugly constructs such as::
def load_api_stuff():
from oscarapi.utils.loading import get_api_class, get_api_classes
api_class = get_api_class(...)
=> fixes get_api_class not finding modules registered with OSCARAPI_OVERRIDE_MODULES

oscarapi/serializers/fields.py, oscarapi/tests/unit/testproduct.py
When you go over the max_size limit, the SpooledTemporaryFile creates a TemporaryFile.
But this TemporaryFile could not be read, because the mode was set to "wb" (write binary).
=> Fix images going over the max file size not being processed.

oscarapi/fixtures/voucher.xml
Since the ids of the condition and benefit of 2 different offers are same, changing one offer updates the other one too. With this PR this issue would be resolved.
=> [Fix] Changing voucher offer's condition updates condition of another offer

.github/workflows/ci.yml, docs/source/topics/settings.rst, oscarapi/download/default.py, oscarapi/permissions.py, oscarapi/serializers/admin/user.py, oscarapi/serializers/basket.py, oscarapi/serializers/checkout.py, oscarapi/serializers/fields.py, oscarapi/serializers/login.py, oscarapi/serializers/product.py, oscarapi/settings.py, oscarapi/tests/unit/testadminapi.py, oscarapi/tests/unit/testlogin.py, oscarapi/tests/unit/testproduct.py, oscarapi/tests/unit/testuser.py, oscarapi/tests/unit/testvoucher.py, oscarapi/urls.py, oscarapi/utils/download.py, oscarapi/views/login.py
This PR cleans up tthe settings that where scattered allover oscarapi.
This was needed to introduce yet another setting: FILE_DOWNLOADER_MODULE.
This makes it possible to override the file downloader, so we can make a bit smarter downloaders that listen to cache headers and such. In the __future__ a smart downloader might be contributed to oscarapi, but it needs internal testing first,
=> File downloader module

.github/workflows/ci.yml, oscarapi/middleware.py, oscarapi/serializers/basket.py, oscarapi/serializers/fields.py, oscarapi/serializers/product.py, oscarapi/signals.py, oscarapi/utils/categories.py, oscarapi/views/basket.py
When using Django 4 with django-oscar-api there are two kinds of errors:
- Ugettext is Removed in Django 4.0
- Signal kwarg providing_args is Disallowed in Django 4.0
Both are fixed with these commits.
=> Fix Django 4 errors

oscarapi/basket/operations.py, oscarapi/middleware.py, oscarapi/tests/unit/testbasket.py, oscarapi/tests/utils.py, setup.py
Unfortunately the tests failed to demonstrate that the basket middleware was broken for anonymous users.
Reverted the change but made sure not to process discounts when saving the basket cookie
Tries to confirm #311 311
=> Fix broken basket middleware

oscarapi/serializers/fields.py
Fixes handling of null product image attributes
When an image product attribute is `null`, the product API would throw the 
following exception:
```
ValueError: The 'value_image' attribute has no file associated with it.
[…]
File "rest_framework/serializers.py", line 522, in to_representation
ret[field.field_name] = field.to_representation(attribute)
File "rest_framework/serializers.py", line 686, in to_representation
return [
File "rest_framework/serializers.py", line 687, in <listcomp>
self.child.to_representation(item) for item in iterable
File "rest_framework/serializers.py", line 522, in to_representation
ret[field.field_name] = field.to_representation(attribute)
File "oscarapi/serializers/fields.py", line 227, in to_representation
return value.value.url
File …
```
=> Fixes handling of null product image attributes

Jenkinsfile, Makefile, oscarapi/utils/models.py, setup.py
=> Jenkinsfile

oscarapi/apps.py
This is configurable since Django 3.2, which is already the required version for oscar-api.
see:
https://docs.djangoproject.com/en/3.2/topics/db/models/#automatic-primary-key-fields
Explicitly telling which field to use if good, it avoids a supious migration like:
$ ./manage.py makemigrations
Migrations for 'oscarapi':
/home/mdk/src/django-oscar/.venv/lib/python3.11/site-packages/oscarapi/migrations/0002_alter_apikey_id.py
- Alter field id on apikey
notice the migration is created in the venv, in oscarapi tree, not in the user project, it won't work anyway.
=> Explicit default_auto_field.

Makefile, oscarapi/serializers/product.py
Added:
`option_group = AttributeOptionGroupSerializer()`
to:
```class OptionSerializer(OscarHyperlinkedModelSerializer):```
in file: oscarapi/serializers/product.py
=> bugfix optiongroupserializer missing

Makefile
This reverts commit 8cf7e38783fdc66beb388b7e70e3c694feec9720.
=> Revert "bugfix optiongroupserializer missing (#344)"

.github/workflows/ci.yml, Jenkinsfile, Makefile, oscarapi/serializers/admin/product.py, oscarapi/tests/unit/testproduct.py
Ignores categories, product_class and children if they are added in the requests to create or update child products.
=> [Fix] Child products should not have product class and categories 

oscarapi/serializers/product.py, oscarapi/tests/unit/testproduct.py, oscarapi/utils/exists.py
---
**Resolves:** https://github.com/django-oscar/django-oscar-api/issues/372
The `options` field in `AttributeOptionGroupSerializer` is defined using:
```python
slug_field="option"
```
This means the serializer works with data like:
```json
[
{"option": "Large"},
{"option": "Medium"}
]
```
However, when updating existing instances, the model receives options as actual `AttributeOption` instances:
```python
[<AttributeOption: Large>, <AttributeOption: Medium>, <AttributeOption: Small>, <AttributeOption: Rokeol>]
```
This mismatch caused `find_existing_attribute_option_group` to fail at detecting duplicates — resulting in **unnecessary creation of duplicate option groups** even when the name and options were the same.
---
Updated `find_existing_attribute_option_group` to:
* Accept and …
=> Prevent duplicate AttributeOptionGroup creation
